version: '3'

volumes:
  bundler_gems:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle && bundle exec rails server -b '0.0.0.0'"
    stdin_open: true
    tty: true
    user: $CURRENT_UID
    volumes:
      - .:/var/app
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
      - "3035:3035"